/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // American Theme Colors (default)
        'liberty-blue': 'var(--color-liberty-blue)',
        'liberty-blue-dark': 'var(--color-liberty-blue-dark)',
        'freedom-red': 'var(--color-freedom-red)',
        'star-white': 'var(--color-star-white)',
        'steel-gray': 'var(--color-steel-gray)',
        'sky-stripe': 'var(--color-sky-stripe)',
        'vintage-gold': 'var(--color-vintage-gold)',
        'land': 'var(--color-land)',
        'land-dark': 'var(--color-land-dark)',

        // Semantic colors (mapped via CSS vars for theming)
        'bg': 'var(--color-bg)',
        'bg-elevated': 'var(--color-bg-elevated)',
        'bg-overlay': 'var(--color-bg-overlay)',
        'surface': 'var(--color-surface)',
        'surface-hover': 'var(--color-surface-hover)',
        'border-color': 'var(--color-border)',
        'border-focus': 'var(--color-border-focus)',

        'text-primary': 'var(--color-text)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-muted': 'var(--color-text-muted)',
        'text-inverse': 'var(--color-text-inverse)',
        'text-border': 'var(--color-text-border)',

        'primary': 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        'primary-light': 'var(--color-primary-light)',
        'primary-dark': 'var(--color-primary-dark)',

        'accent': 'var(--color-accent)',
        'accent-hover': 'var(--color-accent-hover)',

        'success': 'var(--color-success)',
        'warning': 'var(--color-warning)',
        'error': 'var(--color-error)',
      },
      fontFamily: {
        'sans': ['var(--font-sans)'],
        'mono': ['var(--font-mono)'],
        // American theme fonts
        'american-solid': ['hwt-american-solid', 'var(--font-sans)'],
        'american-inset': ['hwt-american-inset', 'var(--font-sans)'],
        'american-stars': ['hwt-american-stars-bottom', 'var(--font-sans)'],
        'american-outline': ['hwt-american-outline', 'var(--font-sans)'],
        // African theme fonts (placeholder - user will provide custom fonts)
        'african-display': ['var(--font-african-display)', 'var(--font-sans)'],
      },
      spacing: {
        '0': 'var(--space-0)',
        '1': 'var(--space-1)',
        '2': 'var(--space-2)',
        '3': 'var(--space-3)',
        '4': 'var(--space-4)',
        '5': 'var(--space-5)',
        '6': 'var(--space-6)',
        '8': 'var(--space-8)',
        '10': 'var(--space-10)',
        '12': 'var(--space-12)',
        '16': 'var(--space-16)',
        '20': 'var(--space-20)',
      },
      fontSize: {
        'xs': 'var(--text-xs)',
        'sm': 'var(--text-sm)',
        'base': 'var(--text-base)',
        'lg': 'var(--text-lg)',
        'xl': 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
        '3xl': 'var(--text-3xl)',
        '4xl': 'var(--text-4xl)',
      },
      borderRadius: {
        'none': 'var(--radius-none)',
        'sm': 'var(--radius-sm)',
        'base': 'var(--radius-base)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        'full': 'var(--radius-full)',
      },
      boxShadow: {
        'sm': 'var(--shadow-sm)',
        'base': 'var(--shadow-base)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
        'xl': 'var(--shadow-xl)',
      },
      zIndex: {
        'base': 'var(--z-base)',
        'docked': 'var(--z-docked)',
        'dropdown': 'var(--z-dropdown)',
        'sticky': 'var(--z-sticky)',
        'banner': 'var(--z-banner)',
        'overlay': 'var(--z-overlay)',
        'modal': 'var(--z-modal)',
        'popover': 'var(--z-popover)',
        'skip-link': 'var(--z-skipLink)',
        'toast': 'var(--z-toast)',
        'tooltip': 'var(--z-tooltip)',
      },
      transitionDuration: {
        'instant': 'var(--duration-instant)',
        'fast': 'var(--duration-fast)',
        'base': 'var(--duration-base)',
        'slow': 'var(--duration-slow)',
        'slower': 'var(--duration-slower)',
      },
    },
  },
  plugins: [],
}
